### ISSUE TITLE
Conflict with plugins using outdated Composer

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#372]
The error:
```
An error of type E_ERROR was caused in line 38 of the file /wp-content/plugins/imagify/vendor/composer/autoload_real.php. Error message: Uncaught Error: Call to undefined method Composer\Autoload\ClassLoader::setClassMapAuthoritative() in /wp-content/plugins/imagify/vendor/composer/autoload_real.php:38
Stack trace:
#0 /wp-content/plugins/imagify/vendor/autoload.php(7): ComposerAutoloaderInitcf5e5b5e6e719606e681127097ead1b2::getLoader()
#1 /wp-content/plugins/imagify/inc/classes/class-imagify-plugin.php(94): require_once('/...')
#2 /wp-content/plugins/imagify/inc/classes/class-imagify-plugin.php(43): Imagify_Plugin->include_files()
#3 /wp-content/plugins/imagify/imagify.php(58): Imagify_Plugin->init()
#4 /wp-includes/class-wp-hook.php(286): _imagify_init('')
...
```
This happens because we set the property `classmap-authoritative` to true in the auto-loader configuration and some plugins are still using old versions of Composer, without this part.

Possible solutions:
- Don't use this property: the aim of this property is to speed up the auto-loader a bit, but this can be considered. It also lists the files that can be included, which adds a layer of security.
- Use [php-scoper](https://github.com/humbug/php-scoper) to namespace the auto-loader. It somehow defeats the point of Composer, but since we're already in WP...
- Detect the missing of the method `setClassMapAuthoritative()` and stop the plugin + display an admin notice inviting to deactivate the faulty plugin (we can use a reflection to locate the culprit).
- Use a custom auto-loader. I'd prefer not to.

**Comment by Screenfeed** [comment]
Closed in #385.
