### ISSUE TITLE
WP CLI Next Generation image AVIF generation in folder fails

### ISSUE THREAD

**Issue by jasperf** [wp-media/imagify-plugin#885]
From the command line I am trying to generate the missing next generation images or AVIF. This as the generation via Dashboard hangs a lot. 

![Screenshot 2024-04-25 at 14 05 03](https://github.com/wp-media/imagify-plugin/assets/344138/0e394e8d-6d66-484a-99f5-aef0cef08d3d)

But the page on usage at https://imagify.io/documentation/how-to-use-wp-cli-for-imagify/ is unclear and so when I run this it fails
```
wp imagify generate-missing-nextgen wp-content/uploads/2024/03
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Imagify\Bulk\Bulk::run_generate_nextgen(), 1 passed in /home/debxxxxxx/domains/domain.com/public_html/wp-content/plugins/imagify/classes/CLI/GenerateMissingNextgenCommand.php on line 19 and exactly 2 expected in /home/debxxxxxx/domains/domain.com/public_html/wp-content/plugins/imagify/classes/Bulk/Bulk.php:223
Stack trace:
#0 /home/debxxxxxx/domains/domain.com/public_html/wp-content/plugins/imagify/classes/CLI/GenerateMissingNextgenCommand.php(19): Imagify\Bulk\Bulk->run_generate_nextgen()
#1 [internal function]: Imagify\CLI\GenerateMissingNextgenCommand->__invoke()
#2 phar:///home/debxxxxxx/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
```

What command should I use?

**Comment by wordpressfan** [comment]
Related ticket: https://secure.helpscout.net/conversation/2609641597/494058/

**Comment by saranshj4** [comment]
https://secure.helpscout.net/conversation/2605674745/493178/

**Comment by saranshj4** [comment]
https://wordpress.org/support/topic/wp-cli-generate-missing-nextgen-not-working/

**Comment by saranshj4** [comment]
https://secure.helpscout.net/conversation/2685771449

**Comment by saranshj4** [comment]
https://secure.helpscout.net/conversation/2819197061/534995?viewId=676697

**Comment by Mil1** [comment]
Hi, when is fixed ? i think is simple issue :

`public function run_generate_nextgen( array $contexts, array $formats ) {`

in cli file : 
`Bulk::get_instance()->run_generate_nextgen( $arguments );`

I found this also in imagify-plugin/inc/functions/api.php : 
`function imagify_generate_nextgen( $contexts ) {
	Imagify\Bulk\Bulk::get_instance()->run_generate_nextgen( $contexts );
}`

Thank to make fix.

**Comment by saranshj4** [comment]
cc: @piotrbak 
https://secure.helpscout.net/conversation/3078337805/587170

**Comment by saranshj4** [comment]
https://secure.helpscout.net/conversation/3097419619/590379?viewId=8160051

**Comment by saranshj4** [comment]
https://onecomhelp.zendesk.com/agent/tickets/17333663

**Comment by Miraeld** [comment]
> [!NOTE]
> Generated by the AI delivery pipeline (orchestrator · Claude Opus 4.8).

**PR:** [#1093](https://github.com/wp-media/imagify-plugin/pull/1093) | **Status:** READY FOR REVIEW

| Stage | Result | Notes |
|---|---|---|
| Grooming | ✅ | effort: S, risk: LOW |
| Challenger | ⏭ Skipped | XS/S + LOW risk + LOW complexity |
| Implementation | ✅ | branch: `fix/885-wp-cli-generate-missing` |
| DOD L2 | ✅ PASS | — |
| Lead Review | ✅ PASS | REQUEST_CHANGES → fixed (tightened test assertion); details on PR #1093 |
| CI | ✅ All Pass | PHP 7.4–8.4, WP 5.9–latest, Codacy, E2E |
| QA | ✅ PASS | static + unit; live run guard-blocked (needs API key); details on PR #1093 |
| Follow-up tickets | #1094 | PHP 8.5 test-infra deprecation (pre-existing) |
